# Generated by Django 5.2 on 2025-04-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundingOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField()),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('opportunity_status', models.CharField(blank=True, max_length=100, null=True)),
                ('funders', models.CharField(blank=True, max_length=500, null=True)),
                ('funders_url', models.URLField(blank=True, null=True)),
                ('funding_type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('award_range', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
