# Generated by Django 5.2 on 2025-04-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingopportunity',
            name='closing_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundingopportunity',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundingopportunity',
            name='opening_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundingopportunity',
            name='publication_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
