# Generated by Django 5.2 on 2025-04-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_alter_fundingopportunity_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingopportunity',
            name='closing_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundingopportunity',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
