# Generated by Django 4.2.23 on 2025-06-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_fundingopportunity_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingopportunity',
            options={'ordering': ['-ai_last_processed', '-id']},
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='ai_analysis',
            field=models.JSONField(blank=True, help_text='AI analysis results', null=True),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='ai_keywords',
            field=models.JSONField(blank=True, help_text='Keywords extracted by AI', null=True),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='ai_last_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='ai_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary', null=True),
        ),
    ]
