# Generated by Django 5.2 on 2026-05-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funding", "0006_fundingopportunity_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingopportunity",
            name="funders_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="fundingopportunity",
            name="funding_type",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="fundingopportunity",
            name="award_range",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="fundingopportunity",
            name="institution",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
