# Generated by Django 5.2 on 2026-05-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funding", "0007_alter_fundingopportunity_field_lengths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingopportunity",
            name="link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
